theme: jekyll-theme-midnight
collections:
  bots:
    output: true
    
title: Botworld Wiki
description: Robopedia, Guides & Infos collected by the community
logo: https://cdn.discordapp.com/emojis/918669937214640269.png
