theme: jekyll-theme-midnight
collections:
  bots:
    output: true
    
# Name of your site (displayed in the header)
name: Botpedia test
# Short bio or description (displayed in the header)
description: trying stuff out
