theme: jekyll-theme-midnight
collections:
  bots:
    output: true
    
title: Botpedia test
description: trying stuff out
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
